apiVersion: v1
kind: Pod
metadata:
    name: webserver
    labels:
        app: demo
spec:
    containers:
    - name: webserver-container
      image: python:3.6
      command: ['python', '-m', 'http.server']
      ports:
      - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']