apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  special.how: very
  special.type: charm

---

apiVersion: v1
kind: Pod
metadata:
    name: webserver-with-configmap
    labels:
        app: demo
spec:
    containers:
    - name: webserver-container
      image: python:3.6
      command: ['python', '-m', 'http.server']
      ports:
      - containerPort: 8000
      env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
    volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: special-config