apiVersion: v1
kind: Service
metadata:
  name: charts
  namespace: kube-system
spec:
  selector:
    app: helm
    component: repo
    layer: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: charts
  namespace: kube-system
  labels:
    app: helm
    component: repo
    layer: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
      component: repo
      layer: backend
  template:
    metadata:
      labels:
        app: helm
        component: repo
        layer: backend
    spec:
      containers:
      - name: charts
        image: xuwenbao/charts
        command: ['/usr/local/bin/helm', 'serve', '--address', '0.0.0.0:80', '--repo-path', '/srv/charts', '--url', 'http://charts.kube-system.svc.cluster.local']
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 15
